# Generated by Django 4.2.2 on 2023-06-28 03:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_alter_ticket_time'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ticket',
        ),
    ]
